#Definimos el tipo de base de datos que vamos usar
quarkus.datasource.db-kind=postgresql

#Definimos el usuario y password que se conecta a la base de datos a usar
quarkus.datasource.username=postgres
quarkus.datasource.password=root

#URL de conexion a la base de datos 
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banco

#Sincronizar lo que tengo en codigo con la base de datos
#En que escenarios se va sincronizar con la base de datos..
## DOS FORMAS DE CREAR DATOS :
# 1 FORMA: Indica a Hibernate que cree las tablas y luego ejecute el import.sql
# pero se eliminan los datos cada vez que insertas
#quarkus.hibernate-orm.database.generation=drop-and-create
# 2 FORMA: es la estrategia 
quarkus.hibernate-orm.database.generation=update

##Cada vez que se ejecuta una consulta a la base de datos se muestra en la consola
#el sql que se esta ejecutando 
quarkus.hibernate-orm.log.sql=true

quarkus.hibernate-orm.sql-load-script=import.sql
 